[[questions]]
question = "What's one effect of calling random.seed(42)"
answers = ["The random numbers are reproducible."]
choices = ["The random numbers are more random.",
    "The computer clock is reset.",
    "The first random number is always 42."]

[[questions]]
question = "When does __name__ == '__main__' equal True in a Python file"
answers = ["When the file is run as a script"]
choices = ["When the file is imported as a module",
    "When the file has a valid name",
    "When the file only has one function"]

[[questions]]
question = "What's the purpose of the built-in zip() function"
answers = ["To iterate over two or more sequences at the same time"]
choices = ["To combine several strings into one",
    "To compress several files into one archive",
    "To get information from the user"]

[[questions]]
question = "What's the name of Python's sorting algorithm"
answers = ["Timsort"]
choices = ["Quicksort", "Merge sort", "Bubble sort"]

[[questions]]
question = "What's the official name of the := operator"
answers = ["Assignment expression"]
choices = ["Named expression",
    "Walrus operator",
    "Colon equals operator"]

[[questions]]
question = "What does dict.get(key) return if key isn't found in dict"
answers = ["None"]
choices = ["key", "True", "False"]

[[questions]]
question = "Which keyword do you use to loop over a given list of elements"
answers = ["for"]
choices = ["while", "each", "loop"]

[[questions]]
question = "Which built-in function can get information from the user"
answers = ["input"]
choices = ["get", "print", "write"]

[[questions]]
question = "When was the first known use of the word 'quiz'"
answers = ["1781"]
choices = ["1771", "1871", "1881"]

[[questions]]
question = "How do you iterate over both indices and elements in an iterable"
answers = ["enumerate(iterable)"]
choices = ["enumerate(iterable, start=1)",
    "range(iterable)",
    "range(iterable, start=1)",]

[[questions]]
question = "Which version of Python is the first with TOML support built in"
answers = ["3.11"]
choices = ["3.9", "3.10", "3.12"]

[[questions]]
question = "How can you run a Python script named quiz.py"
answers = ["python quiz.py", "python -m quiz"]
choices = ["python quiz", "python -m quiz.py"]

